/* 
 * Toggl API
 *
 * Public Toggl API. Note: We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`. In our case it will be `base64(user_name:api_token)`.
 *
 * OpenAPI spec version: 9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TogglAPI.NetStandard.Api;
using TogglAPI.NetStandard.Model;
using TogglAPI.NetStandard.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TogglAPI.NetStandard.Test
{
    /// <summary>
    ///  Class for testing ClientsReportClient
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ClientsReportClientTests
    {
        // TODO uncomment below to declare an instance variable for ClientsReportClient
        //private ClientsReportClient instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ClientsReportClient
            //instance = new ClientsReportClient();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ClientsReportClient
        /// </summary>
        [Test]
        public void ClientsReportClientInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ClientsReportClient
            //Assert.IsInstanceOfType<ClientsReportClient> (instance, "variable 'instance' is a ClientsReportClient");
        }


        /// <summary>
        /// Test the property 'BillableSeconds'
        /// </summary>
        [Test]
        public void BillableSecondsTest()
        {
            // TODO unit test for the property 'BillableSeconds'
        }
        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Test]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'Earnings'
        /// </summary>
        [Test]
        public void EarningsTest()
        {
            // TODO unit test for the property 'Earnings'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'TotalSeconds'
        /// </summary>
        [Test]
        public void TotalSecondsTest()
        {
            // TODO unit test for the property 'TotalSeconds'
        }

    }

}
