/* 
 * Toggl API
 *
 * Public Toggl API. Note: We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`. In our case it will be `base64(user_name:api_token)`.
 *
 * OpenAPI spec version: 9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TogglAPI.NetStandard.Api;
using TogglAPI.NetStandard.Model;
using TogglAPI.NetStandard.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TogglAPI.NetStandard.Test
{
    /// <summary>
    ///  Class for testing ModelsWorkspacePreferences
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelsWorkspacePreferencesTests
    {
        // TODO uncomment below to declare an instance variable for ModelsWorkspacePreferences
        //private ModelsWorkspacePreferences instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelsWorkspacePreferences
            //instance = new ModelsWorkspacePreferences();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelsWorkspacePreferences
        /// </summary>
        [Test]
        public void ModelsWorkspacePreferencesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelsWorkspacePreferences
            //Assert.IsInstanceOfType<ModelsWorkspacePreferences> (instance, "variable 'instance' is a ModelsWorkspacePreferences");
        }


        /// <summary>
        /// Test the property 'AnnualMasterCampaign2018'
        /// </summary>
        [Test]
        public void AnnualMasterCampaign2018Test()
        {
            // TODO unit test for the property 'AnnualMasterCampaign2018'
        }
        /// <summary>
        /// Test the property 'HideStartEndTimes'
        /// </summary>
        [Test]
        public void HideStartEndTimesTest()
        {
            // TODO unit test for the property 'HideStartEndTimes'
        }
        /// <summary>
        /// Test the property 'IncTosAcceptedAt'
        /// </summary>
        [Test]
        public void IncTosAcceptedAtTest()
        {
            // TODO unit test for the property 'IncTosAcceptedAt'
        }
        /// <summary>
        /// Test the property 'IncTosAcceptedBy'
        /// </summary>
        [Test]
        public void IncTosAcceptedByTest()
        {
            // TODO unit test for the property 'IncTosAcceptedBy'
        }
        /// <summary>
        /// Test the property 'InitialPricingPlan'
        /// </summary>
        [Test]
        public void InitialPricingPlanTest()
        {
            // TODO unit test for the property 'InitialPricingPlan'
        }
        /// <summary>
        /// Test the property 'January2018Campaign'
        /// </summary>
        [Test]
        public void January2018CampaignTest()
        {
            // TODO unit test for the property 'January2018Campaign'
        }
        /// <summary>
        /// Test the property 'MasterSignup'
        /// </summary>
        [Test]
        public void MasterSignupTest()
        {
            // TODO unit test for the property 'MasterSignup'
        }
        /// <summary>
        /// Test the property 'ReportLockedAt'
        /// </summary>
        [Test]
        public void ReportLockedAtTest()
        {
            // TODO unit test for the property 'ReportLockedAt'
        }
        /// <summary>
        /// Test the property 'SingleSignOn'
        /// </summary>
        [Test]
        public void SingleSignOnTest()
        {
            // TODO unit test for the property 'SingleSignOn'
        }
        /// <summary>
        /// Test the property 'SsoRequestedAt'
        /// </summary>
        [Test]
        public void SsoRequestedAtTest()
        {
            // TODO unit test for the property 'SsoRequestedAt'
        }

    }

}
