/* 
 * Toggl API
 *
 * Public Toggl API. Note: We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`. In our case it will be `base64(user_name:api_token)`.
 *
 * OpenAPI spec version: 9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TogglAPI.NetStandard.Api;
using TogglAPI.NetStandard.Model;
using TogglAPI.NetStandard.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TogglAPI.NetStandard.Test
{
    /// <summary>
    ///  Class for testing ModelsMobileFeedback
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelsMobileFeedbackTests
    {
        // TODO uncomment below to declare an instance variable for ModelsMobileFeedback
        //private ModelsMobileFeedback instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelsMobileFeedback
            //instance = new ModelsMobileFeedback();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelsMobileFeedback
        /// </summary>
        [Test]
        public void ModelsMobileFeedbackInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelsMobileFeedback
            //Assert.IsInstanceOfType<ModelsMobileFeedback> (instance, "variable 'instance' is a ModelsMobileFeedback");
        }


        /// <summary>
        /// Test the property 'Attachment'
        /// </summary>
        [Test]
        public void AttachmentTest()
        {
            // TODO unit test for the property 'Attachment'
        }
        /// <summary>
        /// Test the property 'AttachmentName'
        /// </summary>
        [Test]
        public void AttachmentNameTest()
        {
            // TODO unit test for the property 'AttachmentName'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'IntercomEnabled'
        /// </summary>
        [Test]
        public void IntercomEnabledTest()
        {
            // TODO unit test for the property 'IntercomEnabled'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'UserID'
        /// </summary>
        [Test]
        public void UserIDTest()
        {
            // TODO unit test for the property 'UserID'
        }

    }

}
