/* 
 * Toggl API
 *
 * Public Toggl API. Note: We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`. In our case it will be `base64(user_name:api_token)`.
 *
 * OpenAPI spec version: 9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TogglAPI.NetStandard.Api;
using TogglAPI.NetStandard.Model;
using TogglAPI.NetStandard.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TogglAPI.NetStandard.Test
{
    /// <summary>
    ///  Class for testing SubscriptionOutData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubscriptionOutDataTests
    {
        // TODO uncomment below to declare an instance variable for SubscriptionOutData
        //private SubscriptionOutData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubscriptionOutData
            //instance = new SubscriptionOutData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubscriptionOutData
        /// </summary>
        [Test]
        public void SubscriptionOutDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubscriptionOutData
            //Assert.IsInstanceOfType<SubscriptionOutData> (instance, "variable 'instance' is a SubscriptionOutData");
        }


        /// <summary>
        /// Test the property 'AutoRenew'
        /// </summary>
        [Test]
        public void AutoRenewTest()
        {
            // TODO unit test for the property 'AutoRenew'
        }
        /// <summary>
        /// Test the property 'BillingPeriodInMonths'
        /// </summary>
        [Test]
        public void BillingPeriodInMonthsTest()
        {
            // TODO unit test for the property 'BillingPeriodInMonths'
        }
        /// <summary>
        /// Test the property 'CampaignAvailable'
        /// </summary>
        [Test]
        public void CampaignAvailableTest()
        {
            // TODO unit test for the property 'CampaignAvailable'
        }
        /// <summary>
        /// Test the property 'CancelDate'
        /// </summary>
        [Test]
        public void CancelDateTest()
        {
            // TODO unit test for the property 'CancelDate'
        }
        /// <summary>
        /// Test the property 'CardDetails'
        /// </summary>
        [Test]
        public void CardDetailsTest()
        {
            // TODO unit test for the property 'CardDetails'
        }
        /// <summary>
        /// Test the property 'CompanyId'
        /// </summary>
        [Test]
        public void CompanyIdTest()
        {
            // TODO unit test for the property 'CompanyId'
        }
        /// <summary>
        /// Test the property 'ContactDetails'
        /// </summary>
        [Test]
        public void ContactDetailsTest()
        {
            // TODO unit test for the property 'ContactDetails'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'CurrentPeriodEndsAt'
        /// </summary>
        [Test]
        public void CurrentPeriodEndsAtTest()
        {
            // TODO unit test for the property 'CurrentPeriodEndsAt'
        }
        /// <summary>
        /// Test the property 'CurrentPeriodStartsAt'
        /// </summary>
        [Test]
        public void CurrentPeriodStartsAtTest()
        {
            // TODO unit test for the property 'CurrentPeriodStartsAt'
        }
        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Test]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'Enterprise'
        /// </summary>
        [Test]
        public void EnterpriseTest()
        {
            // TODO unit test for the property 'Enterprise'
        }
        /// <summary>
        /// Test the property 'IsSubscriptionBeta'
        /// </summary>
        [Test]
        public void IsSubscriptionBetaTest()
        {
            // TODO unit test for the property 'IsSubscriptionBeta'
        }
        /// <summary>
        /// Test the property 'IsUnified'
        /// </summary>
        [Test]
        public void IsUnifiedTest()
        {
            // TODO unit test for the property 'IsUnified'
        }
        /// <summary>
        /// Test the property 'LastInvoice'
        /// </summary>
        [Test]
        public void LastInvoiceTest()
        {
            // TODO unit test for the property 'LastInvoice'
        }
        /// <summary>
        /// Test the property 'LastPayment'
        /// </summary>
        [Test]
        public void LastPaymentTest()
        {
            // TODO unit test for the property 'LastPayment'
        }
        /// <summary>
        /// Test the property 'LastPricingPlanId'
        /// </summary>
        [Test]
        public void LastPricingPlanIdTest()
        {
            // TODO unit test for the property 'LastPricingPlanId'
        }
        /// <summary>
        /// Test the property 'NewSignupTrial'
        /// </summary>
        [Test]
        public void NewSignupTrialTest()
        {
            // TODO unit test for the property 'NewSignupTrial'
        }
        /// <summary>
        /// Test the property 'NextPaymentDate'
        /// </summary>
        [Test]
        public void NextPaymentDateTest()
        {
            // TODO unit test for the property 'NextPaymentDate'
        }
        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Test]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'PlanName'
        /// </summary>
        [Test]
        public void PlanNameTest()
        {
            // TODO unit test for the property 'PlanName'
        }
        /// <summary>
        /// Test the property 'PricingPlanId'
        /// </summary>
        [Test]
        public void PricingPlanIdTest()
        {
            // TODO unit test for the property 'PricingPlanId'
        }
        /// <summary>
        /// Test the property 'RenewalAt'
        /// </summary>
        [Test]
        public void RenewalAtTest()
        {
            // TODO unit test for the property 'RenewalAt'
        }
        /// <summary>
        /// Test the property 'RenewalDate'
        /// </summary>
        [Test]
        public void RenewalDateTest()
        {
            // TODO unit test for the property 'RenewalDate'
        }
        /// <summary>
        /// Test the property 'SeatCostInCents'
        /// </summary>
        [Test]
        public void SeatCostInCentsTest()
        {
            // TODO unit test for the property 'SeatCostInCents'
        }
        /// <summary>
        /// Test the property 'Seats'
        /// </summary>
        [Test]
        public void SeatsTest()
        {
            // TODO unit test for the property 'Seats'
        }
        /// <summary>
        /// Test the property 'Site'
        /// </summary>
        [Test]
        public void SiteTest()
        {
            // TODO unit test for the property 'Site'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'SubscriptionCreatedAt'
        /// </summary>
        [Test]
        public void SubscriptionCreatedAtTest()
        {
            // TODO unit test for the property 'SubscriptionCreatedAt'
        }
        /// <summary>
        /// Test the property 'SubscriptionPeriod'
        /// </summary>
        [Test]
        public void SubscriptionPeriodTest()
        {
            // TODO unit test for the property 'SubscriptionPeriod'
        }
        /// <summary>
        /// Test the property 'TrialAvailable'
        /// </summary>
        [Test]
        public void TrialAvailableTest()
        {
            // TODO unit test for the property 'TrialAvailable'
        }
        /// <summary>
        /// Test the property 'TrialEndDate'
        /// </summary>
        [Test]
        public void TrialEndDateTest()
        {
            // TODO unit test for the property 'TrialEndDate'
        }
        /// <summary>
        /// Test the property 'TrialStartDate'
        /// </summary>
        [Test]
        public void TrialStartDateTest()
        {
            // TODO unit test for the property 'TrialStartDate'
        }

    }

}
