/* 
 * Toggl API
 *
 * Public Toggl API. Note: We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`. In our case it will be `base64(user_name:api_token)`.
 *
 * OpenAPI spec version: 9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = TogglAPI.NetStandard.Client.SwaggerDateConverter;

namespace TogglAPI.NetStandard.Model
{
    /// <summary>
    /// MePostSessionHandlerRequestBody
    /// </summary>
    [DataContract]
    public partial class MePostSessionHandlerRequestBody :  IEquatable<MePostSessionHandlerRequestBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MePostSessionHandlerRequestBody" /> class.
        /// </summary>
        /// <param name="rememberMe">If true, the session cookie will be valid for 24 hours, otherwise until the browser is closed.</param>
        public MePostSessionHandlerRequestBody(bool? rememberMe = default(bool?))
        {
            this.RememberMe = rememberMe;
        }
        
        /// <summary>
        /// If true, the session cookie will be valid for 24 hours, otherwise until the browser is closed
        /// </summary>
        /// <value>If true, the session cookie will be valid for 24 hours, otherwise until the browser is closed</value>
        [DataMember(Name="remember_me", EmitDefaultValue=false)]
        public bool? RememberMe { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MePostSessionHandlerRequestBody {\n");
            sb.Append("  RememberMe: ").Append(RememberMe).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MePostSessionHandlerRequestBody);
        }

        /// <summary>
        /// Returns true if MePostSessionHandlerRequestBody instances are equal
        /// </summary>
        /// <param name="input">Instance of MePostSessionHandlerRequestBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MePostSessionHandlerRequestBody input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RememberMe == input.RememberMe ||
                    (this.RememberMe != null &&
                    this.RememberMe.Equals(input.RememberMe))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RememberMe != null)
                    hashCode = hashCode * 59 + this.RememberMe.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
