/* 
 * Toggl API
 *
 * Public Toggl API. Note: We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`. In our case it will be `base64(user_name:api_token)`.
 *
 * OpenAPI spec version: 9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using TogglAPI.NetStandard.Client;
using TogglAPI.NetStandard.Model;

namespace TogglAPI.NetStandard.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITimelineApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Delete all timeline data
        /// </summary>
        /// <remarks>
        /// Delete all timeline data for the current user
        /// </remarks>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        void TimelineDelete ();

        /// <summary>
        /// Delete all timeline data
        /// </summary>
        /// <remarks>
        /// Delete all timeline data for the current user
        /// </remarks>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> TimelineDeleteWithHttpInfo ();
        /// <summary>
        /// Get timeline events
        /// </summary>
        /// <remarks>
        /// Get timeline events
        /// </remarks>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Unix timestamp of the start date (optional)</param>
        /// <param name="endDate">Unix timestamp of the end date (optional)</param>
        /// <returns>List&lt;ModelsTimelineEvent&gt;</returns>
        List<ModelsTimelineEvent> TimelineGet (int? startDate = null, int? endDate = null);

        /// <summary>
        /// Get timeline events
        /// </summary>
        /// <remarks>
        /// Get timeline events
        /// </remarks>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Unix timestamp of the start date (optional)</param>
        /// <param name="endDate">Unix timestamp of the end date (optional)</param>
        /// <returns>ApiResponse of List&lt;ModelsTimelineEvent&gt;</returns>
        ApiResponse<List<ModelsTimelineEvent>> TimelineGetWithHttpInfo (int? startDate = null, int? endDate = null);
        /// <summary>
        /// Save timeline events
        /// </summary>
        /// <remarks>
        /// Save timeline events and returns timeline settings
        /// </remarks>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timelinePost">timeline events (optional)</param>
        /// <returns>ModelsTimelineSettings</returns>
        ModelsTimelineSettings TimelinePost (List<ModelsTimelineEvent> timelinePost = null);

        /// <summary>
        /// Save timeline events
        /// </summary>
        /// <remarks>
        /// Save timeline events and returns timeline settings
        /// </remarks>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timelinePost">timeline events (optional)</param>
        /// <returns>ApiResponse of ModelsTimelineSettings</returns>
        ApiResponse<ModelsTimelineSettings> TimelinePostWithHttpInfo (List<ModelsTimelineEvent> timelinePost = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Delete all timeline data
        /// </summary>
        /// <remarks>
        /// Delete all timeline data for the current user
        /// </remarks>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task TimelineDeleteAsync ();

        /// <summary>
        /// Delete all timeline data
        /// </summary>
        /// <remarks>
        /// Delete all timeline data for the current user
        /// </remarks>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> TimelineDeleteAsyncWithHttpInfo ();
        /// <summary>
        /// Get timeline events
        /// </summary>
        /// <remarks>
        /// Get timeline events
        /// </remarks>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Unix timestamp of the start date (optional)</param>
        /// <param name="endDate">Unix timestamp of the end date (optional)</param>
        /// <returns>Task of List&lt;ModelsTimelineEvent&gt;</returns>
        System.Threading.Tasks.Task<List<ModelsTimelineEvent>> TimelineGetAsync (int? startDate = null, int? endDate = null);

        /// <summary>
        /// Get timeline events
        /// </summary>
        /// <remarks>
        /// Get timeline events
        /// </remarks>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Unix timestamp of the start date (optional)</param>
        /// <param name="endDate">Unix timestamp of the end date (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;ModelsTimelineEvent&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ModelsTimelineEvent>>> TimelineGetAsyncWithHttpInfo (int? startDate = null, int? endDate = null);
        /// <summary>
        /// Save timeline events
        /// </summary>
        /// <remarks>
        /// Save timeline events and returns timeline settings
        /// </remarks>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timelinePost">timeline events (optional)</param>
        /// <returns>Task of ModelsTimelineSettings</returns>
        System.Threading.Tasks.Task<ModelsTimelineSettings> TimelinePostAsync (List<ModelsTimelineEvent> timelinePost = null);

        /// <summary>
        /// Save timeline events
        /// </summary>
        /// <remarks>
        /// Save timeline events and returns timeline settings
        /// </remarks>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timelinePost">timeline events (optional)</param>
        /// <returns>Task of ApiResponse (ModelsTimelineSettings)</returns>
        System.Threading.Tasks.Task<ApiResponse<ModelsTimelineSettings>> TimelinePostAsyncWithHttpInfo (List<ModelsTimelineEvent> timelinePost = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TimelineApi : ITimelineApi
    {
        private TogglAPI.NetStandard.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TimelineApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TimelineApi(String basePath)
        {
            this.Configuration = new TogglAPI.NetStandard.Client.Configuration { BasePath = basePath };

            ExceptionFactory = TogglAPI.NetStandard.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TimelineApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TimelineApi(TogglAPI.NetStandard.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = TogglAPI.NetStandard.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = TogglAPI.NetStandard.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public TogglAPI.NetStandard.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public TogglAPI.NetStandard.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Delete all timeline data Delete all timeline data for the current user
        /// </summary>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        public void TimelineDelete ()
        {
             TimelineDeleteWithHttpInfo();
        }

        /// <summary>
        /// Delete all timeline data Delete all timeline data for the current user
        /// </summary>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> TimelineDeleteWithHttpInfo ()
        {

            var localVarPath = "/timeline";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TimelineDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Delete all timeline data Delete all timeline data for the current user
        /// </summary>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task TimelineDeleteAsync ()
        {
             await TimelineDeleteAsyncWithHttpInfo();

        }

        /// <summary>
        /// Delete all timeline data Delete all timeline data for the current user
        /// </summary>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> TimelineDeleteAsyncWithHttpInfo ()
        {

            var localVarPath = "/timeline";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TimelineDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Get timeline events Get timeline events
        /// </summary>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Unix timestamp of the start date (optional)</param>
        /// <param name="endDate">Unix timestamp of the end date (optional)</param>
        /// <returns>List&lt;ModelsTimelineEvent&gt;</returns>
        public List<ModelsTimelineEvent> TimelineGet (int? startDate = null, int? endDate = null)
        {
             ApiResponse<List<ModelsTimelineEvent>> localVarResponse = TimelineGetWithHttpInfo(startDate, endDate);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get timeline events Get timeline events
        /// </summary>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Unix timestamp of the start date (optional)</param>
        /// <param name="endDate">Unix timestamp of the end date (optional)</param>
        /// <returns>ApiResponse of List&lt;ModelsTimelineEvent&gt;</returns>
        public ApiResponse< List<ModelsTimelineEvent> > TimelineGetWithHttpInfo (int? startDate = null, int? endDate = null)
        {

            var localVarPath = "/timeline";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (startDate != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "start_date", startDate)); // query parameter
            if (endDate != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "end_date", endDate)); // query parameter

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TimelineGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ModelsTimelineEvent>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<ModelsTimelineEvent>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ModelsTimelineEvent>)));
        }

        /// <summary>
        /// Get timeline events Get timeline events
        /// </summary>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Unix timestamp of the start date (optional)</param>
        /// <param name="endDate">Unix timestamp of the end date (optional)</param>
        /// <returns>Task of List&lt;ModelsTimelineEvent&gt;</returns>
        public async System.Threading.Tasks.Task<List<ModelsTimelineEvent>> TimelineGetAsync (int? startDate = null, int? endDate = null)
        {
             ApiResponse<List<ModelsTimelineEvent>> localVarResponse = await TimelineGetAsyncWithHttpInfo(startDate, endDate);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get timeline events Get timeline events
        /// </summary>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Unix timestamp of the start date (optional)</param>
        /// <param name="endDate">Unix timestamp of the end date (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;ModelsTimelineEvent&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<ModelsTimelineEvent>>> TimelineGetAsyncWithHttpInfo (int? startDate = null, int? endDate = null)
        {

            var localVarPath = "/timeline";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (startDate != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "start_date", startDate)); // query parameter
            if (endDate != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "end_date", endDate)); // query parameter

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TimelineGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ModelsTimelineEvent>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<ModelsTimelineEvent>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ModelsTimelineEvent>)));
        }

        /// <summary>
        /// Save timeline events Save timeline events and returns timeline settings
        /// </summary>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timelinePost">timeline events (optional)</param>
        /// <returns>ModelsTimelineSettings</returns>
        public ModelsTimelineSettings TimelinePost (List<ModelsTimelineEvent> timelinePost = null)
        {
             ApiResponse<ModelsTimelineSettings> localVarResponse = TimelinePostWithHttpInfo(timelinePost);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Save timeline events Save timeline events and returns timeline settings
        /// </summary>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timelinePost">timeline events (optional)</param>
        /// <returns>ApiResponse of ModelsTimelineSettings</returns>
        public ApiResponse< ModelsTimelineSettings > TimelinePostWithHttpInfo (List<ModelsTimelineEvent> timelinePost = null)
        {

            var localVarPath = "/timeline";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (timelinePost != null && timelinePost.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(timelinePost); // http body (model) parameter
            }
            else
            {
                localVarPostBody = timelinePost; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TimelinePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ModelsTimelineSettings>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ModelsTimelineSettings) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ModelsTimelineSettings)));
        }

        /// <summary>
        /// Save timeline events Save timeline events and returns timeline settings
        /// </summary>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timelinePost">timeline events (optional)</param>
        /// <returns>Task of ModelsTimelineSettings</returns>
        public async System.Threading.Tasks.Task<ModelsTimelineSettings> TimelinePostAsync (List<ModelsTimelineEvent> timelinePost = null)
        {
             ApiResponse<ModelsTimelineSettings> localVarResponse = await TimelinePostAsyncWithHttpInfo(timelinePost);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Save timeline events Save timeline events and returns timeline settings
        /// </summary>
        /// <exception cref="TogglAPI.NetStandard.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="timelinePost">timeline events (optional)</param>
        /// <returns>Task of ApiResponse (ModelsTimelineSettings)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ModelsTimelineSettings>> TimelinePostAsyncWithHttpInfo (List<ModelsTimelineEvent> timelinePost = null)
        {

            var localVarPath = "/timeline";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (timelinePost != null && timelinePost.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(timelinePost); // http body (model) parameter
            }
            else
            {
                localVarPostBody = timelinePost; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TimelinePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ModelsTimelineSettings>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ModelsTimelineSettings) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ModelsTimelineSettings)));
        }

    }
}
