/* 
 * Toggl API
 *
 * Public Toggl API. Note: We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`. In our case it will be `base64(user_name:api_token)`.
 *
 * OpenAPI spec version: 9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using TogglAPI.NetStandard.Client;
using TogglAPI.NetStandard.Api;
using TogglAPI.NetStandard.Model;

namespace TogglAPI.NetStandard.Test
{
    /// <summary>
    ///  Class for testing OrganizationsOwnerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class OrganizationsOwnerApiTests
    {
        private OrganizationsOwnerApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new OrganizationsOwnerApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrganizationsOwnerApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' OrganizationsOwnerApi
            //Assert.IsInstanceOfType(typeof(OrganizationsOwnerApi), instance, "instance is a OrganizationsOwnerApi");
        }

        
        /// <summary>
        /// Test GetOwnershipTransfer
        /// </summary>
        [Test]
        public void GetOwnershipTransferTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? organizationId = null;
            //int? transferId = null;
            //var response = instance.GetOwnershipTransfer(organizationId, transferId);
            //Assert.IsInstanceOf<ModelsTransfer> (response, "response is ModelsTransfer");
        }
        
        /// <summary>
        /// Test GetOwnershipTransfers
        /// </summary>
        [Test]
        public void GetOwnershipTransfersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? organizationId = null;
            //string ongoing = null;
            //var response = instance.GetOwnershipTransfers(organizationId, ongoing);
            //Assert.IsInstanceOf<List<ModelsTransfer>> (response, "response is List<ModelsTransfer>");
        }
        
        /// <summary>
        /// Test PostOwnershipTransfer
        /// </summary>
        [Test]
        public void PostOwnershipTransferTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? organizationId = null;
            //var response = instance.PostOwnershipTransfer(organizationId);
            //Assert.IsInstanceOf<ModelsTransfer> (response, "response is ModelsTransfer");
        }
        
        /// <summary>
        /// Test PostOwnershipTransferActions
        /// </summary>
        [Test]
        public void PostOwnershipTransferActionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? organizationId = null;
            //int? transferId = null;
            //string action = null;
            //var response = instance.PostOwnershipTransferActions(organizationId, transferId, action);
            //Assert.IsInstanceOf<ModelsTransfer> (response, "response is ModelsTransfer");
        }
        
    }

}
