name: Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_VERSION: ${{ format('0.2.{0}+{1}', $GITHUB_RUN_NUMBER, $GITHUB_SHA) }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Pack
      run: dotnet pack TogglAPI.NetStandard/TogglAPI.NetStandard.csproj -c Release -p:Version=$VERSION -o /output
    - name: Upload Package
      uses: actions/upload-artifact@v2.2.4
      with:
        name: package
        path: /output
        retention-days: 0
