name: Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Pack
      env:
        PACKAGE_VERSION: ${{ format('0.3.{0}+{1}', github.run_number, github.sha) }}
      run: dotnet pack -c Release -p:Version=$PACKAGE_VERSION -o ./output
    - name: Upload Package
      uses: actions/upload-artifact@v2.2.4
      with:
        name: package
        path: ./output
        retention-days: 0
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Download Artifact
      uses: actions/download-artifact@v2.0.10
      with:
        name: package
        path: ./output
    - name: Upload to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        PACKAGE_NAME: ${{ format('TogglAPI.NetStandard.0.3.{0}.nupkg', github.run_number) }}
      run: dotnet nuget push ./output/$PACKAGE_NAME -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
